フロントテスト追加

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -1,18 +1,30 @@
 version: 0.2
-
 phases:
-  install:
-    commands:
-      - echo "Installing necessary tools..."
-      - sudo yum install -y epel-release   # EPELリポジトリを手動でインストール
-      - sudo yum install -y curl
   pre_build:
     commands:
-      - echo "Pre-build phase..."
+      - echo Logging in to Amazon ECR...
+      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/seikabutu
+      - REPOSITORY_URI=513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/seikabutu
+      - echo Logging in to Docker Hub...
+      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
+
   build:
     commands:
-      - echo "Testing access to the website..."
-      - curl -I http://a46c8267f8b5a46e1a8d9e3e87cbe44d-944449116.ap-northeast-1.elb.amazonaws.com/
+      - echo Building the Docker image...
+      - docker build -t $REPOSITORY_URI:latest ./nginx
+      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
+      - echo "Checking if the web page is accessible..."
+      - URL="http://a46c8267f8b5a46e1a8d9e3e87cbe44d-944449116.ap-northeast-1.elb.amazonaws.com/"
+      - curl --head --silent --fail $URL > /dev/null
+      - |
+        if [ $? -eq 0 ]; then
+          echo "Test passed: Web page is accessible."
+        else
+          echo "Test failed: Web page is not accessible."
+          exit 1
+        fi
+
   post_build:
     commands:
-      - echo "Build completed"
+      - echo Pushing the Docker image to ECR...
+      - docker push $REPOSITORY_URI:latest
