フロントテスト追加

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -13,9 +13,16 @@ phases:
       - echo Building the Docker image...
       - docker build -t $REPOSITORY_URI:latest ./nginx
       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
-      - echo "Running UI tests..."
-      - npm install puppeteer
-      - node test.js
+      - echo "Checking if the web page is accessible..."
+      - URL="http://a46c8267f8b5a46e1a8d9e3e87cbe44d-944449116.ap-northeast-1.elb.amazonaws.com/"
+      - curl --head --silent --fail $URL > /dev/null
+      - |
+        if [ $? -eq 0 ]; then
+          echo "Test passed: Web page is accessible."
+        else
+          echo "Test failed: Web page is not accessible."
+          exit 1
+        fi
 
   post_build:
     commands:
